In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('StudentsPerformance.csv')

In [3]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
#for info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [5]:
#head method

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [8]:
df.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [9]:
#df[colname]

df['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [10]:
df[['gender','lunch']]

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
..      ...           ...
995  female      standard
996    male  free/reduced
997  female  free/reduced
998  female      standard
999  female  free/reduced

[1000 rows x 2 columns]

In [11]:
df[['gender','lunch','writing score']]

     gender         lunch  writing score
0    female      standard             74
1    female      standard             88
2    female      standard             93
3      male  free/reduced             44
4      male      standard             75
..      ...           ...            ...
995  female      standard             95
996    male  free/reduced             55
997  female  free/reduced             65
998  female      standard             77
999  female  free/reduced             86

[1000 rows x 3 columns]

In [12]:
# slicing

df.iloc[:,:]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [13]:
import pandas as pd

In [14]:
df=pd.read_csv('StudentsPerformance.csv')

In [15]:
df.iloc[:,:]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
df.iloc[:,2]

0       bachelor's degree
1            some college
2         master's degree
3      associate's degree
4            some college
              ...
995       master's degree
996           high school
997           high school
998          some college
999          some college
Name: parental level of education, Length: 1000, dtype: str

In [17]:
df.iloc[0,1]

'group B'

In [18]:
df.iloc[1:,1:]

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,group C,some college,standard,completed,69,90,88
2,group B,master's degree,standard,none,90,95,93
3,group A,associate's degree,free/reduced,none,47,57,44
4,group C,some college,standard,none,76,78,75
5,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...
995,group E,master's degree,standard,completed,88,99,95
996,group C,high school,free/reduced,none,62,55,55
997,group C,high school,free/reduced,completed,59,71,65
998,group D,some college,standard,completed,68,78,77
999,group D,some college,free/reduced,none,77,86,86

In [19]:
df.iloc[[0,3]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
3,male,group A,associate's degree,free/reduced,none,47,57,44

In [20]:
df.iloc[[0,3],[0,2]]

   gender parental level of education
0  female           bachelor's degree
3    male          associate's degree

In [21]:
df.iloc[[0,3],:]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
3,male,group A,associate's degree,free/reduced,none,47,57,44

In [22]:
df.iloc[0:3]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [23]:
df.iloc[:,'gender']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [ ]:
df.iloc[:,['gender']]

IndexError: .iloc requires numeric indexers, got ['gender']

In [ ]:
df.iloc[::2]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
6,female,group B,some college,standard,completed,88,95,92
8,male,group D,high school,free/reduced,completed,64,64,67
...,...,...,...,...,...,...,...,...
990,male,group E,high school,free/reduced,completed,86,81,75
992,female,group D,associate's degree,free/reduced,none,55,76,76
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55
998,female,group D,some college,standard,completed,68,78,77

In [ ]:
df.iloc[-1,:]

gender                               female
race/ethnicity                      group D
parental level of education    some college
lunch                          free/reduced
test preparation course                none
math score                               77
reading score                            86
writing score                            86
Name: 999, dtype: object

In [ ]:
##loc slicing

df.loc[:,:]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.loc[:,:,2]

IndexingError: Too many indexers

In [ ]:
df.loc[:,'parental level of education']

0       bachelor's degree
1            some college
2         master's degree
3      associate's degree
4            some college
              ...
995       master's degree
996           high school
997           high school
998          some college
999          some college
Name: parental level of education, Length: 1000, dtype: str

In [ ]:
df.loc[0:5:1,'gender']

0    female
1    female
2    female
3      male
4      male
5    female
Name: gender, dtype: str

In [ ]:
df.loc[[0,3]]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
3,male,group A,associate's degree,free/reduced,none,47,57,44

In [ ]:
df.loc[0,['gender']]

gender    female
Name: 0, dtype: str

In [ ]:
df.loc[10:,'gender':'lunch']

     gender race/ethnicity parental level of education         lunch
10     male        group C          associate's degree      standard
11     male        group D          associate's degree      standard
12   female        group B                 high school      standard
13     male        group A                some college      standard
14   female        group A             master's degree      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

[990 rows x 4 columns]

In [ ]:
df.loc[0]

gender                                    female
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                    72
reading score                                 72
writing score                                 74
Name: 0, dtype: object

In [ ]:
df.loc[0,'gender','lunch']

IndexingError: Too many indexers

In [ ]:
df.loc[0:10:2,['gender','lunch']]

    gender         lunch
0   female      standard
2   female      standard
4     male      standard
6   female      standard
8     male  free/reduced
10    male      standard

In [ ]:
#filter based on condition

df['gender']=='female'

0       True
1       True
2       True
3      False
4      False
       ...
995     True
996    False
997     True
998     True
999     True
Name: gender, Length: 1000, dtype: bool

In [ ]:
df['gender']!='female'

0      False
1      False
2      False
3       True
4       True
       ...
995    False
996     True
997    False
998    False
999    False
Name: gender, Length: 1000, dtype: bool

In [ ]:
df[df['gender']=='female']

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df['gender','lunch']=='female','standard'

KeyError: ('gender', 'lunch')

In [ ]:
#filter female record and lunch is standard
df[(df['gender']=='female') & (df['lunch']=='standard')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
984,female,group C,some high school,standard,none,74,75,82
986,female,group C,associate's degree,standard,none,40,59,51
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77

In [ ]:
#Filter female records those who scored above 70 in maths
[(df['gender']=='female') & (df['math score']>70)]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
36,female,group D,associate's degree,standard,none,74,81,83
...,...,...,...,...,...,...,...,...
979,female,group C,associate's degree,standard,none,91,95,94
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#filter male records and lunch is standard
df[(df['gender']=='male') & (df['lunch']=='standard')]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
4,male,group C,some college,standard,none,76,78,75
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
13,male,group A,some college,standard,completed,78,72,70
16,male,group C,high school,standard,none,88,89,86
...,...,...,...,...,...,...,...,...
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
994,male,group A,high school,standard,none,63,63,62

In [ ]:
# And final count of filtered records from 1 & 2
#Count of female records with 70 above will be 170 records
#Count of male records and lunch stander will be 316 records

#it is shown in result at the end of the table

In [ ]:
df['gender'].unique()
df['race/ethnicity'].unique()

<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

In [ ]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [ ]:
#For getting all catogorical columns unique values and store in in the column names
l=['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

In [ ]:
for i in l:
    print(f"{i} => {df[i].unique()}")

gender => <StringArray>
['female', 'male']
Length: 2, dtype: str
race/ethnicity => <StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
parental level of education => <StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
lunch => <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
test preparation course => <StringArray>
['none', 'completed']
Length: 2, dtype: str

In [ ]:
#to get the count of the unique values
for i in l:
    print(f"{i} => {df[i].nunique()}")

gender => 2
race/ethnicity => 5
parental level of education => 6
lunch => 2
test preparation course => 2

In [ ]:
# by using len method to find count
for i in l:
    a= df[i].unique()
    b=len(a)
    print(f"{i} => {b}")

gender => 2
race/ethnicity => 5
parental level of education => 6
lunch => 2
test preparation course => 2

In [ ]:
# value_counts()

df['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [ ]:
import pandas

In [ ]:
## isnull()

#Using list created a dataframe table
data=[[22,None],[None,None],[None,25000],[30,40000],[60,150000]]
col=['age','sal']
pandas.DataFrame(data,columns=col)

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
#Using dictionary created a dataframe table
df=pandas.DataFrame({'age':[22,None,None,30,60],'sal':[None,None,25000,40000,150000]})
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
df.mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [ ]:
df.mean("sal")

C:\Users\kruth\AppData\Local\Temp\ipykernel_1908\847834635.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  df.mean("sal")

ValueError: No axis named sal for object type DataFrame

In [ ]:
df.mean(numeric_only=True)

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
df.mean(numeric_only=True,axis=0)

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
df.mean(numeric_only=True,axis=1)

0      72.666667
1      82.333333
2      92.666667
3      49.333333
4      76.333333
         ...
995    94.000000
996    57.333333
997    65.000000
998    74.333333
999    83.000000
Length: 1000, dtype: float64

In [ ]:
df.median(numeric_only=True,axis=0)

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [ ]:
df.median(numeric_only=True,axis=1)

0      72.0
1      88.0
2      93.0
3      47.0
4      76.0
       ...
995    95.0
996    55.0
997    65.0
998    77.0
999    86.0
Length: 1000, dtype: float64

In [ ]:
df.mode(numeric_only=True,axis=0)

   math score  reading score  writing score
0          65             72             74

In [ ]:
df.mode(numeric_only=True,axis=1)

        0     1     2
0    72.0   NaN   NaN
1    69.0  88.0  90.0
2    90.0  93.0  95.0
3    44.0  47.0  57.0
4    75.0  76.0  78.0
..    ...   ...   ...
995  88.0  95.0  99.0
996  55.0   NaN   NaN
997  59.0  65.0  71.0
998  68.0  77.0  78.0
999  86.0   NaN   NaN

[1000 rows x 3 columns]

In [ ]:
df.agg(['min','max','mean'])

TypeError: Cannot perform reduction 'mean' with string dtype

In [ ]:
df[['reading score','math score', 'writing score']].agg(['max','mean','min'])

      reading score  math score  writing score
max         100.000     100.000        100.000
mean         69.169      66.089         68.054
min          17.000       0.000         10.000

In [ ]:
df.agg({'reading score':'max',
        'writing score':'min',
        'math score': 'mean'})

reading score    100.000
writing score     10.000
math score        66.089
dtype: float64

In [ ]:
df.mode()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some college,standard,none,65,72,74

In [ ]:
#Shape

df.shape

(1000, 8)

In [ ]:
#Count
df.count()

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                          1000
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [ ]:
#isnull

df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#Using dictionary created a dataframe table
df=pandas.DataFrame({'age':[22,None,None,30,60],'sal':[None,None,25000,40000,150000]})
df

NameError: name 'pandas' is not defined

In [ ]:
import pandas as pd

In [ ]:
#Using dictionary created a dataframe table
df=pd.DataFrame({'age':[22,None,None,30,60],'sal':[None,None,25000,40000,150000]})
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
#isnull
df.isna()

     age    sal
0  False   True
1   True   True
2   True  False
3  False  False
4  False  False

In [ ]:
#for getting the count of null values of each column
df.isna().sum()

age    2
sal    2
dtype: int64

In [ ]:
#for getting the count of null values of entire table
df.isna().sum().sum()

np.int64(4)

In [ ]:
#not null

#notnull()/notna()


df.notnull()

     age    sal
0   True  False
1  False  False
2  False   True
3   True   True
4   True   True

In [ ]:
df.notna()

     age    sal
0   True  False
1  False  False
2  False   True
3   True   True
4   True   True

In [ ]:
df.notnull().sum()

age    3
sal    3
dtype: int64

In [ ]:
df.notnull().sum().sum()

np.int64(6)

In [ ]:
df['age'].notna()

0     True
1    False
2    False
3     True
4     True
Name: age, dtype: bool

In [ ]:
df[df['age'].notna()]

    age       sal
0  22.0       NaN
3  30.0   40000.0
4  60.0  150000.0

In [24]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
#Using dictionary created a dataframe table
df=pd.DataFrame({'age':[22,None,None,30,60],'sal':[None,None,25000,40000,150000]})
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
#fillna(value)

#df.fillna(0)

    age       sal
0  22.0       0.0
1   0.0       0.0
2   0.0   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
#df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [ ]:
#df=df.fillna(0)

In [ ]:
#df

    age       sal
0  22.0       0.0
1   0.0       0.0
2   0.0   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [40]:
#df.fillna(value,inplace=True)
#df=df.fillna(0,inplace=True) #-> None
#df.fillna(0,inplace=True)

In [41]:
#df

In [44]:
#Using dictionary created a dataframe table
df=pd.DataFrame({'age':[22,None,None,30,60],'sal':[None,None,25000,40000,150000]})
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [45]:
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [49]:
#df.fillna({'age':df['age'].mean(),

#           'sal':df['sal'].median()})

In [50]:
df

    age       sal
0  22.0       NaN
1   NaN       NaN
2   NaN   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [51]:
df.fillna(method='ffill')

TypeError: NDFrame.fillna() got an unexpected keyword argument 'method'

In [52]:
df.ffill()

    age       sal
0  22.0       NaN
1  22.0       NaN
2  22.0   25000.0
3  30.0   40000.0
4  60.0  150000.0

In [53]:
df.bfill()

    age       sal
0  22.0   25000.0
1  30.0   25000.0
2  30.0   25000.0
3  30.0   40000.0
4  60.0  150000.0